# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

trigger:
- main

pool:
  vmImage: 'ubuntu-latest'

steps:
- script: echo Hello, world!
  displayName: 'Run a one-line script'

- script: |
    sudo apt-get install python3-venv
    python3 -m venv venv
    source venv/bin/activate
    python -m pip install --upgrade pip
    python -m pip install -r requirements.txt
  displayName: 'Set up the env'

- script: |
    source venv/bin/activate
    python run.py
  displayName: 'Build the list of CVEs with exploits'

- task: PublishPipelineArtifact@1
  inputs:
    targetPath: '$(System.DefaultWorkingDirectory)/cves.txt'
    artifact: 'cves_txt'
    publishLocation: 'pipeline'

- task: GitHubRelease@1
  displayName: 'GitHub release (create)'
  inputs:
    gitHubConnection: 'JNDataCDC_1'
    repositoryName: 'JNData-CDC/vulns-with-exploits'
    tagSource: userSpecifiedTag
    tag: '$(Build.BuildNumber)'
    assets: '$(System.DefaultWorkingDirectory)/_JNData-CDC.vulns-with-exploits/cves.txt'
    addChangeLog: false